### ISSUE TITLE
bidiftnxtra

### ISSUE THREAD

**Issue by shmehry** [tex-xet/xepersian#18]
سلام.
 من هنگام استفاده همزمان از بسته bidiftnxtra و array یا tabu با مشکل مواجه می‌شوم.
با توجه به اینکه ممکن است این یک باگ باشد در اینجا آن را مطرح نمودم.
 از اینکه به زبان انگلیسی تسلط ندارم و مشکل را به زبان فارسی نوشتم عذر خواهی میکنم 
با تشکر
مهری

**Comment by vafa** [comment]
This issue is the `bidi` package's issue and has nothing to do with the `xepersian` package. Therefore, I have created the corresponding issue (tex-xet/bidi#44) in the `bidi` package repository and closed this issue.

**Comment by vafa** [comment]
I now accept donations to the xepersian package. Anyone can donate any amount to the xepersian package. If you are interested to donate to the xepersian package, then please email me at `persian-tex@tug.org` and request my bank account details.

The donations allow me to spend more time working on the xepersian package and make it even better. If you know that some other people may also be interested in donating to the xepersian package development, please let them know.
