### ISSUE TITLE
How to use a special font for a character in different environments?

### ISSUE THREAD

**Issue by mortezaoa71** [tex-xet/xepersian#19]
I'm trying to achieve a `$v$` with special font attached to this question. It's used in `align`, `$$ ... $$` (display math mode), `equation` and other environments. I want to change only `v` font in an equation so the rest of text or equation must be typeset in the default font. I've realized that TeX does  not recognize my intended font.
````latex
\documentclass{article}
\usepackage{amsmath}
\usepackage{fontspec}
\usepackage{unicode-math}
\usepackage{ptext}
\usepackage{xepersian}
\settextfont{IRLotus}
\setdigitfont[Numbers={Lining,Proportional},
Scale=0.8]{Persian Modern}
         \begin{document} 
         \ptext [1]
             \begin{equation}
\vee=at \ 0123456789
         \end{equation}
             \begin{equation}
v=at \ 0123456789
         \end{equation}
         \begin{equation}
         \setmathfont{Benguiat_Gothic-Medium}
v=at \ 0123456789
         \end{equation}
         $v=at \ 0123456789$
         \end{document} 
````
![v](https://cloud.githubusercontent.com/assets/24843336/21576362/4e5e321e-cf41-11e6-90ad-a2111721de3a.jpg)
[v.docx](https://github.com/tex-xet/xepersian/files/679502/v.docx)

**Comment by vafa** [comment]
I do not know the context of your problem but I believe your approach to solve your problem is flawed. 

To answer your question, you can define a `\setmymathvfont` command that will just change the font of the letter `v` in math font; the following code does this but it adds a new math family (`MYMATHV`).

````latex
\documentclass{article}
\usepackage{amsmath}
\usepackage{ptext}
\usepackage{xepersian}
\settextfont{Yas}
\setdigitfont{Yas}
\ExplSyntaxOn
\DeclareDocumentCommand \setmymathvfont { o m }{%
  \__fontspec_pass_args:nnn \__my_setmymathvfont:nn {#1} {#2} }

\cs_new:Nn \__my_setmymathvfont:nn
 {
  \fontspec_set_family:Nnn \my_mathv_family {#1} {#2}
  \DeclareSymbolFont{MYMATHV}   {\g_fontspec_encoding_tl}{\my_mathv_family} {m}{n}
\SetMathCode{`v}{\mathalpha}{MYMATHV}{`v}
}
\ExplSyntaxOff
\setmymathvfont{Arial}
         \begin{document} 
         \ptext [1]
             \begin{equation}
\vee=at \ 0123456789
         \end{equation}
             \begin{equation}
v=at \ 0123456789
         \end{equation}
         \begin{equation}
v=at \ 0123456789
         \end{equation}
         $v=at \ 0123456789$
         \end{document} 
````

**Comment by mortezaoa71** [comment]
Thanks a lot.It works well.
but when I use `\mathit` to make it italic ,the font is shown as default font and it doesn't work properly(MYMATHV doesn't work).what should I do?

**Comment by vafa** [comment]
Do you want to type $v$ and get an italic `v`? then, you need to replace the line
````latex
\SetMathCode{`v}{\mathalpha}{MYMATHV}{`v}
````
with the following line
````latex
\SetMathCode{`v}{\mathalpha}{MYMATHV}{"1D463}
````
[`U+1D463`](http://www.fileformat.info/info/unicode/char/1d463/index.htm) is the **_Unicode Character 'MATHEMATICAL ITALIC SMALL V'_**. Your font needs to have this character; if it does not, again your approach is wrong.

**Comment by mortezaoa71** [comment]
Thank you again.unfortunately,as your guess,either for my favorite font or for all of my fonts,it doesn't work properly.it just shows little rectangles instead of  italic`v`. is there better approach to achieve italic `v `?

**Comment by mortezaoa71** [comment]
I tested an idea which was based on downloading italic font of my favorite font.I downloaded the italic font and put it in `\setmymathvfont{<font>}`.it's working properly.is it reasonable?

**Comment by vafa** [comment]
If you have installed a complete set of family of a font (at least having regular and italic shape), you can use the following code; TeX will find italic shape automatically.

````latex
\documentclass{article}
\usepackage{amsmath}
\usepackage{ptext}
\usepackage{xepersian}
\settextfont{Yas}
\setdigitfont{Yas}
\ExplSyntaxOn
\DeclareDocumentCommand \setmymathvfont { o m }{%
  \__fontspec_pass_args:nnn \__my_setmymathvfont:nn {#1} {#2} }

\cs_new:Nn \__my_setmymathvfont:nn
 {
  \fontspec_set_family:Nnn \my_mathv_family {#1} {#2}
  \DeclareSymbolFont{MYMATHV}   {\g_fontspec_encoding_tl}{\my_mathv_family} {m}{it}
\SetMathCode{`v}{\mathalpha}{MYMATHV}{`v}
}
\ExplSyntaxOff
\setmymathvfont{Arial}
         \begin{document} 
         \ptext [1]
             \begin{equation}
\vee=at \ 0123456789
         \end{equation}
             \begin{equation}
v=at \ 0123456789
         \end{equation}
         \begin{equation}
v=at \ 0123456789
         \end{equation}
         $v=at \ 0123456789$
         \end{document} 
````

**Comment by mortezaoa71** [comment]
thanks for your great answers

**Comment by vafa** [comment]
I now accept donations to the xepersian package. Anyone can donate any amount to the xepersian package. If you are interested to donate to the xepersian package, then please email me at `persian-tex@tug.org` and request my bank account details.

The donations allow me to spend more time working on the xepersian package and make it even better. If you know that some other people may also be interested in donating to the xepersian package development, please let them know.
