### ISSUE TITLE
xepersian font problem

### ISSUE THREAD

**Issue by vahid22002** [tex-xet/xepersian#21]
hello
I have a problem with fonts in "xepersian"
For example when i want to use xepersian and amsthm it produces 2 warnings which are
first
LaTeX Font Warning: Font shape `TU/BNazanin(0)/m/it' undefined
(Font)              using `TU/BNazanin(0)/m/n' instead on input line 10. 

second
*************************************************
* fontspec warning: "language-not-exist"
* 
* Language 'Parsi' not available for font 'B Nazanin' with script 'Parsi'.
*  'Default' language used instead.
*************************************************
I use Winedt 10 and MikTex
[1.zip](https://github.com/tex-xet/xepersian/files/777220/1.zip)

**Comment by vafa** [comment]
You obviously did not bother to read the documentation! You can activate fake bold and fake slant fonts (if your font does not have bold and italic shapes) by

````latex
\settextfont[Language=Default]{B Nazanin}[AutoFakeBold,AutoFakeSlant]
````

**Comment by vafa** [comment]
I now accept donations to the xepersian package. Anyone can donate any amount to the xepersian package. If you are interested to donate to the xepersian package, then please email me at `persian-tex@tug.org` and request my bank account details.

The donations allow me to spend more time working on the xepersian package and make it even better. If you know that some other people may also be interested in donating to the xepersian package development, please let them know.
