### ISSUE TITLE
some unexpected space in footnote with computeautoilg and extrafootnotefeatures

### ISSUE THREAD

**Issue by javadr** [tex-xet/xepersian#23]
Hi, 

Using computeautoilg with extrafootnotefeatures causes some extra space between footnote text and footnotemark. The following code shows the issue.

```latex
\documentclass{article}
\usepackage[extrafootnotefeatures=on,computeautoilg=on]{xepersian}
\settextfont{Yas}

\begin{document}
متن با پانویس\footnote{پانویس}
\end{document}
```

![image](https://cloud.githubusercontent.com/assets/1178221/23935325/a33e5a4e-0960-11e7-850a-83a202eb5416.png)

As you better know the usual way is like below, 
![image](https://cloud.githubusercontent.com/assets/1178221/23935356/dc4e51cc-0960-11e7-8f23-9c01afa4e49a.png)

and with just computeautoilg as shown on the next pic there also is some extra space. 
![image](https://cloud.githubusercontent.com/assets/1178221/23935411/20f1958c-0961-11e7-8007-a1a9e21ce94a.png)

**Comment by javadr** [comment]
it also causes some extra space in the text too. 

```latex
\documentclass{article}
\usepackage[computeautoilg=on]{xepersian}
\settextfont{Yas}

\begin{document}
متن با پانویس\footnote{پانویس} و مقداری دیگر متن.
\end{document}
```

![image](https://cloud.githubusercontent.com/assets/1178221/23936933/0dc4a0a4-096a-11e7-8064-00b9ed0de752.png)
and the normal is like following
![image](https://cloud.githubusercontent.com/assets/1178221/23936953/23c43842-096a-11e7-9c7a-e12f504e44c0.png)

**Comment by vafa** [comment]
I now accept donations to the xepersian package. Anyone can donate any amount to the xepersian package. If you are interested to donate to the xepersian package, then please email me at `persian-tex@tug.org` and request my bank account details.

The donations allow me to spend more time working on the xepersian package and make it even better. If you know that some other people may also be interested in donating to the xepersian package development, please let them know.
