### ISSUE TITLE
Issues with algorithmicx in both latin and persian environments

### ISSUE THREAD

**Issue by thedamnedrhino** [tex-xet/xepersian#27]
I'm using the *xepersian* package together with the *algorithmicx* package and I'm having some issues.
In the `persian` environment out of the *algorithmicx* commands that I've tried, i.e: `\ForAll`, `\Function` and `\If` conditionals, only the `\If` conditional commands are translated and the other ones are in english.  
My issue though is with the `latin` environment. In the `latin` environment the other commands are fine (`\ForAll` , `\Function`), but nothing is displayed for `\If` and `\Else`. Although the condition is displayed and the following lines are indented.

**Comment by thedamnedrhino** [comment]
It seems like the issue was with the template I was using. Sorry for the false alarm.

**Comment by vafa** [comment]
I now accept donations to the xepersian package. Anyone can donate any amount to the xepersian package. If you are interested to donate to the xepersian package, then please email me at `persian-tex@tug.org` and request my bank account details.

The donations allow me to spend more time working on the xepersian package and make it even better. If you know that some other people may also be interested in donating to the xepersian package development, please let them know.
