### ISSUE TITLE
enumerate problem using polyglossia and Xepersian

### ISSUE THREAD

**Issue by Elfengour** [tex-xet/xepersian#28]
I'm using the packages `\polyglossia` and `\Xepersian` , I have a problem with third level enumerate, I cannot use `\Alph` numbering in the whole document. It is impossible to use `\Alph` numbering whether for `\subfigure` or Third level list etc.
This is my MWE:

`\documentclass[12pt,a4paper]{book}

\usepackage[nonamebreak, square, comma, sort&compress]{natbib}

\usepackage{polyglossia}

\setmainlanguage[calendar=gregorian, numerals=maghrib]{arabic}
\newfontfamily\arabicfont[Script=Arabic, Scale=1.5]{Amiri}
\setotherlanguage{english}
%
\usepackage{xepersian}
\settextfont{Amiri}
\setlatintextfont[Scale=1.5]{Amiri}
%
\begin{document}

 كز هنا في الحديث على  نظام زي‌تك لأنه أحد أفضل الحلول المتاحة  \citep{ماجدة2012تطوير}
 نفترض هنا وجود معرفة مسبقة
 \cite{kopka2004guide}
\begin{enumerate}
\item Test one
\item Test two
\begin{enumerate}%problem
\item Test one one
\item Test two two
\end{enumerate}%problem
\item Test three
\item Test four
\end{enumerate}

\bibliographystyle{asa-fa}
\bibliography{MyReferences}

\end{document}`

**Comment by Elfengour** [comment]
This is my MWE:
`\documentclass[12pt,a4paper]{book}

\usepackage[nonamebreak, square, comma, sort&compress]{natbib}

\usepackage{polyglossia}

\setmainlanguage[calendar=gregorian, numerals=maghrib]{arabic}
\newfontfamily\arabicfont[Script=Arabic, Scale=1.5]{Amiri}
\setotherlanguage{english}
%
\usepackage{xepersian}
\settextfont{Amiri}
\setlatintextfont[Scale=1.5]{Amiri}
%
\begin{document}

 كز هنا في الحديث على  نظام زي‌تك لأنه أحد أفضل الحلول المتاحة  \citep{ماجدة2012تطوير}
 نفترض هنا وجود معرفة مسبقة
 \cite{kopka2004guide}
\begin{enumerate}
\item Test one
\item Test two
\begin{enumerate}%problem
\item Test one one
\item Test two two
\end{enumerate}%problem
\item Test three
\item Test four
\end{enumerate}

\bibliographystyle{asa-fa}
\bibliography{MyReferences}

\end{document}`

**Comment by Elfengour** [comment]
`\documentclass[12pt,a4paper]{book}

\usepackage[nonamebreak, square, comma, sort&compress]{natbib}

\usepackage{polyglossia}

\setmainlanguage[calendar=gregorian, numerals=maghrib]{arabic}
\newfontfamily\arabicfont[Script=Arabic, Scale=1.5]{Amiri}
\setotherlanguage{english}
%
\usepackage{xepersian}
\settextfont{Amiri}
\setlatintextfont[Scale=1.5]{Amiri}
%
\begin{document}

 كز هنا في الحديث على  نظام زي‌تك لأنه أحد أفضل الحلول المتاحة  \citep{ماجدة2012تطوير}
 نفترض هنا وجود معرفة مسبقة
 \cite{kopka2004guide}
\begin{enumerate}
\item Test one
\item Test two
\begin{enumerate}%problem
\item Test one one
\item Test two two
\end{enumerate}%problem
\item Test three
\item Test four
\end{enumerate}

\bibliographystyle{asa-fa}
\bibliography{MyReferences}

\end{document}`

**Comment by Elfengour** [comment]
> \documentclass[12pt,a4paper]{book}

\usepackage[nonamebreak, square, comma, sort&compress]{natbib}

\usepackage{polyglossia}

\setmainlanguage[calendar=gregorian, numerals=maghrib]{arabic}
\newfontfamily\arabicfont[Script=Arabic, Scale=1.5]{Amiri}
\setotherlanguage{english}
%
\usepackage{xepersian}
\settextfont{Amiri}
\setlatintextfont[Scale=1.5]{Amiri}
%
\begin{document}

 كز هنا في الحديث على  نظام زي‌تك لأنه أحد أفضل الحلول المتاحة  \citep{ماجدة2012تطوير}
 نفترض هنا وجود معرفة مسبقة
 \cite{kopka2004guide}
\begin{enumerate}
\item Test one
\item Test two
\begin{enumerate}%problem
\item Test one one
\item Test two two
\end{enumerate}%problem
\item Test three
\item Test four
\end{enumerate}

\bibliographystyle{asa-fa}
\bibliography{MyReferences}

\end{document}

**Comment by vafa** [comment]
Dear @Elfengour 

Thanks for your bug report. Using `xepersian` and `polyglossia` together is a bad idea. On the other hand, I am afraid that this is a `polyglossia` bug and you will need to contact `polyglossia` author. Sorry!

**Comment by vafa** [comment]
I now accept donations to the bidi package. Anyone can donate any amount to the bidi package using [My PayPal.Me](https://www.paypal.me/persiantex).

The donations allow me to spend more time working on the bidi package and make it even better. If you know that some other people may also be interested in donating to the bidi package development, please let them know.
