### ISSUE TITLE
xepersian problem with longtable and section

### ISSUE THREAD

**Issue by ehsang1855** [tex-xet/xepersian#30]
سلام
  هنگام استفاده از جداول بزرگ مکان نوشتن بخش ها تغییر می کند.
فایل های قبل از ورود جدول و بعد از ورود جدول پیوست شده است.

`
\documentclass[12pt,a4paper]{report}

\usepackage{multicol}

\usepackage{longtable}

\usepackage{hyperref}

\usepackage{graphicx}

\usepackage{xepersian}

\settextfont{Parastoo Print}

\begin{document}

\chapter{تست}

این را برای تست می نویسم

\end{document}
`

[table_befor.pdf](https://github.com/tex-xet/xepersian/files/1255164/table_befor.pdf)

`
\documentclass[12pt,a4paper]{report}

\usepackage{multicol}

\usepackage{longtable}

\usepackage{hyperref}

\usepackage{graphicx}

\usepackage{xepersian}

\settextfont{Parastoo Print}

\begin{document}

\chapter{تست}

این را برای تست می نویسم

\begin{center}

\begin{longtable}{|p{4cm}|p{6cm}|p{3cm}|}

\hline

  \rl{نمونه}

   & توضیح & دستور \\

  \hline

\end{longtable}

\end{center}

\end{document}
`

[table_after.pdf](https://github.com/tex-xet/xepersian/files/1255163/table_after.pdf)

**Comment by vafa** [comment]
This is a duplicate of tex-xet/bidi#29.

**Comment by vafa** [comment]
I now accept donations to the xepersian package. Anyone can donate any amount to the xepersian package. If you are interested to donate to the xepersian package, then please email me at `persian-tex@tug.org` and request my bank account details.

The donations allow me to spend more time working on the xepersian package and make it even better. If you know that some other people may also be interested in donating to the xepersian package development, please let them know.
