### ISSUE TITLE
\LTRfootmarkstyle doesn't work properly without using paragraphfootnotes

### ISSUE THREAD

**Issue by javadr** [tex-xet/xepersian#31]
As you mentioned in http://qa.parsilatex.com/18642, by bidi version 19.5 the \footmarkstyle can change the footnote mark style, but in the last version of bidi (31.2) and xepersian(19.1) the following code doesn't work properly! 
```latex
\documentclass{article}
\usepackage[extrafootnotefeatures]{xepersian}
\settextfont{Yas}
\LTRfootmarkstyle{\textsuperscript{\persianfont #1}}
%\paragraphfootnotes
\begin{document}
\LTRfootnote{text}  \LTRfootnote{text}  \LTRfootnote{text}  \LTRfootnote{text} 
\footnote{مقداری متن} \footnote{مقداری متن} 
\footnote{مقداری متن که می‌تواند خیلی طولانی هم باشد}
و دوباره متن%
\LTRfootnote{text}
\end{document}
```
![screenshot-20170829151404-746x204](https://user-images.githubusercontent.com/1178221/29817311-cc092ca2-8ccc-11e7-9ecb-dfcc59653b1c.png)

By the way, as I remembered the default footmarkstyle even for \LTRfootnote was persian font, but in the recent version it is changed to latin font. 

P.S. with \paragraphfootnotes there is no problem.

**Comment by vafa** [comment]
If you read my answer carefully, I have said that

> بنابراین اگر قصد داشته باشید شماره زیرنویس لاتین در حالت چندستونه و پاراگرافی در پایین صفحه لاتین باشد، نمونه زیر این کار را انجتم می‌دهد

which I meant that it is designed for every single footnote style except plain. So this is not something new and it was a feature by design. The plain footnote style more or less follows the default LaTeX behaviour.

**Comment by vafa** [comment]
I now accept donations to the xepersian package. Anyone can donate any amount to the xepersian package. If you are interested to donate to the xepersian package, then please email me at `persian-tex@tug.org` and request my bank account details.

The donations allow me to spend more time working on the xepersian package and make it even better. If you know that some other people may also be interested in donating to the xepersian package development, please let them know.
