### ISSUE TITLE
Default direction of typesetting paragraph footnotes with xepersian have changed in recent updates.  (form RTL to LTR)

### ISSUE THREAD

**Issue by javadr** [tex-xet/xepersian#32]
Using \paragraphfootnotes with xepersian typeset the footnotes from left to right, but it should be typeset from right to left (like the way worked before new updates). 
Is there any reason that this default behavior changed in new version of bidi and xepersian?

```latex
\documentclass{article}
\usepackage[extrafootnotefeatures]{xepersian}
\settextfont{Yas}
\LTRfootmarkstyle{\textsuperscript{\latinfont #1}}
\paragraphfootnotes
%\setRTLparagraphfootnotes
\begin{document}
\LTRfootnote{text}  \LTRfootnote{text}  \LTRfootnote{text}  \LTRfootnote{text} 
\footnote{مقداری متن} \footnote{مقداری متن} 
\footnote{مقداری متن که می‌تواند خیلی طولانی هم باشد}
و دوباره متن%
\LTRfootnote{text}
\end{document}
```

![screenshot-20170829163607-627x62](https://user-images.githubusercontent.com/1178221/29820133-a528ffde-8cd8-11e7-8b14-c1bc37fce09a.png)

**Comment by vafa** [comment]
The default direction of paragraph footnotes was LTR since day one and I have not made any change to the code. Please note that you do not need to use `\LTRfootmarkstyle` as the `xepersian` does this for you in a better way.

**Comment by javadr** [comment]
You are right, I made a mistake. But what do you think about making \setRTLparagraphfootnotes as default with xepersian because everything in a persian document should be typeset RTL except there is a acceptable reason to do LTR. In this case I think(suggest) it's better to RTL be the default direction for paragraph footnotes.

P.S. 
1- Final decision is up to you.;=)
2- As I remember in previous version we've to use `\LTRfootmarkstyle` command for making footmark style latin, but in new version there is no need to it. 
Do you remember in which version of bidi this change happened?

**Comment by vafa** [comment]
The main reason for implementing paragraph footnotes was that there could be a lot of LTR footnotes on a given page and so the author wanted to save space and when you think about it, it really makes sense as if you are translating a work with a lot of foreign names, you want to put the names in their native languages in the footnotes which is usually left to right. So for this reason, I think having the default direction of paragraph footnotes as LTR makes more sense. On the other hand, if I want to change it (after 8 years), I would be introducing back incompatibility and it would upset a considerable number of users.

For your second question, I am not really sure as I have to check the issues and commit history.

**Comment by vafa** [comment]
I now accept donations to the xepersian package. Anyone can donate any amount to the xepersian package. If you are interested to donate to the xepersian package, then please email me at `persian-tex@tug.org` and request my bank account details.

The donations allow me to spend more time working on the xepersian package and make it even better. If you know that some other people may also be interested in donating to the xepersian package development, please let them know.
