### ISSUE TITLE
Xepersian and Poliglossia packages conflict 

### ISSUE THREAD

**Issue by Elfengour** [tex-xet/xepersian#35]

**Comment by Elfengour** [comment]
I am using Polyglossia as a main package for a thesis  is Arabic  language and Persian-bib for bibliography, the only problem i found is the Latin comma (,) inside Arabic references, it should be this (،). here is the MWE:
`\begin{filecontents}{SomeReferences.bib}
@article{Baker02limits,
author = {Baker,, Simon and Kanade,, Takeo},
title = {Limits on Super-Resolution and How to Break Them},
journal = {IEEE Trans. Pattern Anal. Mach. Intell.},
volume = {24},
number = {9},
year = {2002},
issn = {0162-8828},
pages = {1167--1183},
publisher = {IEEE Computer Society},
address = {Washington, DC, USA}
}
@CONFERENCE{Amintoosi87afzayesh,
AUTHOR =       {امین‌طوسی,محمود and مزینی,ناصر and  فتحی,محمود},
TITLE =        {افزایش وضوح ناحیه‌ای},
BOOKTITLE =    {چهاردهمین کنفرانس ملی سالانه انجمن کامپیوتر ایران},
YEAR =         {1387},
ORGANIZATION = {دانشگاه امیرکبیر},
ADDRESS =      {تهران، ایران},
month =          {اسفند},
pages = {101--108},
LANGUAGE =     {Persian}
}
\end{filecontents}

\documentclass[a4paper]{article}
\usepackage{color}
\usepackage[linktocpage=true,colorlinks,citecolor=blue,pagebackref=true]{hyperref}%
\usepackage[nonamebreak]{natbib}%nonamebreak,numbers,
\usepackage[top=30mm, bottom=30mm, left=30mm, right=30mm]{geometry}
%%
\usepackage[utf8]{inputenc}
\usepackage{polyglossia}
\usepackage[T1]{fontenc}
\setotherlanguage{english}
\setotherlanguage{persian}
\newfontfamily\englishfont{Amiri}[Scale=1.5]%
\setotherlanguage{french}
\newfontfamily\arabicfont[Script=Arabic]{Amiri}
\setmainlanguage[calendar=gregorian, numerals=maghrib, locale=morocco, abjadjimnotail=false]{arabic}
%
\usepackage{xepersian}
\settextfont[Scale=1]{XB Zar}
%
\begin{document}
%
\Latincite{Baker02limits}\\
\citep{Amintoosi87afzayesh}\\
%     
 \bibliographystyle{asa-fa}
 \bibliography{SomeReferences}

\end{document}`


*here you can find the question about this https://tex.stackexchange.com/questions/404691/persian-bib-with-polyglossia-and-xepersian-packages

**Comment by vafa** [comment]
Do not use `xepersian` together with `polyglossia`.

**Comment by vafa** [comment]
I now accept donations to the bidi package. Anyone can donate any amount to the bidi package using [My PayPal.Me](https://www.paypal.me/persiantex).

The donations allow me to spend more time working on the bidi package and make it even better. If you know that some other people may also be interested in donating to the bidi package development, please let them know.
