### ISSUE TITLE
Persian-bib and Legatures=text

### ISSUE THREAD

**Issue by Elfengour** [tex-xet/xepersian#36]
I try to use Persian-bib with Xepersian, but the command Mapping={} or Ligatures=TeX in \settextfont  inverts the comma in persian bibliography, Here is my MWE and .Zip file:
`\begin{filecontents}{SomeReferences.bib}
@article{Baker02limits,
author = {Baker,, Simon and Kanade,, Takeo},
title = {Limits on Super-Resolution and How to Break Them},
journal = {IEEE Trans. Pattern Anal. Mach. Intell.},
volume = {24},
number = {9},
year = {2002},
issn = {0162-8828},
pages = {1167--1183},
publisher = {IEEE Computer Society},
address = {Washington, DC, USA}
}
@CONFERENCE{Amintoosi87afzayesh,
AUTHOR =       {امین‌طوسی,محمود and مزینی,ناصر and  فتحی,محمود},
TITLE =        {افزایش وضوح ناحیه‌ای},
BOOKTITLE =    {چهاردهمین کنفرانس ملی سالانه انجمن کامپیوتر ایران},
YEAR =         {1387},
ORGANIZATION = {دانشگاه امیرکبیر},
ADDRESS =      {تهران ایران},
month =          {اسفند},
pages = {101--108},
LANGUAGE =     {Persian}
}
\end{filecontents}

\documentclass[a4paper]{article}
\usepackage{color}
\usepackage[linktocpage=true,colorlinks,citecolor=blue,pagebackref=true]{hyperref}%
\usepackage[nonamebreak]{natbib}
\usepackage[top=30mm, bottom=30mm, left=30mm, right=30mm]{geometry}
%%

\usepackage{xepersian}
\settextfont[Scale=1, Ligatures=TeX]{XB Zar}
%
   \begin{document}
   \Latincite{Baker02limits}\\
   \citep{Amintoosi87afzayesh}\\ 
   \bibliographystyle{asa-fa}
   \bibliography{SomeReferences}
   \end{document}`
[MWE_Comma.zip](https://github.com/tex-xet/xepersian/files/1585053/MWE_Comma.zip)
![bib2](https://user-images.githubusercontent.com/28195778/34329214-e634b03c-e8ee-11e7-982a-0d25c1ba3de6.png)

**Comment by vafa** [comment]
It is because you deactivated `parsidigits` mapping. It is not just about digits but also other things such as coma as well.

**Comment by vafa** [comment]
I now accept donations to the bidi package. Anyone can donate any amount to the bidi package using [My PayPal.Me](https://www.paypal.me/persiantex).

The donations allow me to spend more time working on the bidi package and make it even better. If you know that some other people may also be interested in donating to the bidi package development, please let them know.
