### ISSUE TITLE
The \setdigitfont command does not match with tag in texlive 2017.

### ISSUE THREAD

**Issue by shapour-m** [tex-xet/xepersian#38]
## Brief outline of the bug
When we use `\setdigitfont` command, `\tag` and `\eqref` does not work correctly.

## Your minimal example showing the bug

```latex
\documentclass[12pt]{article}
\usepackage{mathtools}
\usepackage[%
inlinemathdigits=default,%
displaymathdigits=persian%
]{xepersian}
\settextfont{Yas}
\setdigitfont{Yas}
\begin{document}
\begin{align}
4!&=4\cdot3\cdot2\cdot1 = 24\tag{a--2}  \\  
7!&=7\cdot6\cdot5\cdot4\cdot3\cdot2\cdot1=5040 \tag{a--3}
\end{align}	
\begin{latin}
\begin{align}
4!&=4\cdot3\cdot2\cdot1 = 24\tag{a--2}  \\  
7!&=7\cdot6\cdot5\cdot4\cdot3\cdot2\cdot1=5040 \tag{a--3}
\end{align}
\end{latin}
\begin{equation}\tag{eq:1}\label{2}
4\sin(\psi)\sin(\dfrac{\pi}{3}+\psi)\sin(\dfrac{\pi}{3}-\psi)=\sin(3\psi)
\end{equation}
ارجاع به آن: مطابق اتحاد
\eqref{2}
نتیجه می‌گیریم ...
  
\end{document}
```
Thanks for your responsibility. 
This issue was originally raised [here](http://qa.parsilatex.com/28741/%D8%AF%D8%B3%D8%AA%D9%88%D8%B1-setdigitfont-%D8%A7%D8%B1%D8%AC%D8%A7%D8%B9-%D8%AF%D8%A7%D8%AF%D9%86-%D8%AA%DA%A9%D9%84%D8%A7%DB%8C%D9%88-2017-%D8%B3%D8%A7%D8%B2%DA%AF%D8%A7%D8%B1-%D9%86%DB%8C%D8%B3%D8%AA-%DA%86%D8%B1%D8%A7%D8%9F)

## Log (and possibly PDF) file  
[madad.pdf](https://github.com/tex-xet/xepersian/files/1633190/madad.pdf)
[untitled-1.log](https://github.com/tex-xet/xepersian/files/1633202/untitled-1.log)

**Comment by vafa** [comment]
Where is your log and PDF files?

**Comment by shapour-m** [comment]
Excuse me. I reeded it

**Comment by vafa** [comment]
This is not `xepersian` bug; it is the engine behavior. If you are not convinced, then run `xetex` on the following tex file and see the result for yourself.

````tex
\input bidi
\font\test="Yas:script=arab" at 50pt
\setRTL
\test
a-1

a-\char"200F\relax1

a-\char"200F\relax\kern0pt1

a-\kern0pt\char"200F\relax1

a\kern0pt-\char"200F\relax\kern0pt1

a\kern0pt-\kern0pt\char"200F\relax1
\bye
````

Here are my log and PDF files.

[test.log](https://github.com/tex-xet/xepersian/files/1634519/test.log)
[test.pdf](https://github.com/tex-xet/xepersian/files/1634521/test.pdf)

In your minimal example, as a safe guard, always use `\lr` for latin alphabets.

````tex
\documentclass[12pt]{article}
\usepackage{mathtools}
\usepackage[%
inlinemathdigits=default,%
displaymathdigits=persian%
]{xepersian}
\settextfont{Yas}
\setdigitfont{Yas}
\begin{document}
\begin{align}
4!&=4\cdot3\cdot2\cdot1 = 24\tag{\lr{a}--2}  \\  
7!&=7\cdot6\cdot5\cdot4\cdot3\cdot2\cdot1=5040 \tag{\lr{a}--3}
\end{align}	
\begin{latin}
\begin{align}
4!&=4\cdot3\cdot2\cdot1 = 24\tag{a--2}  \\  
7!&=7\cdot6\cdot5\cdot4\cdot3\cdot2\cdot1=5040 \tag{a--3}
\end{align}
\end{latin}
\begin{equation}\tag{\lr{eq}:1}\label{2}
4\sin(\psi)\sin(\dfrac{\pi}{3}+\psi)\sin(\dfrac{\pi}{3}-\psi)=\sin(3\psi)
\end{equation}
ارجاع به آن: مطابق اتحاد
\eqref{2}
نتیجه می‌گیریم ...
  
\end{document}
````

Anyways, you would need to use `\lr` for latin otherwise your output looks ugly.

**Comment by shapour-m** [comment]
Exactly you are right. Thanks my master Vafa.

**Comment by vafa** [comment]
I found a way to fix this so your original example should work with version `20.7` of the `xepersian` package.

**Comment by shapour-m** [comment]
Thanks a lot. I wait to receive the version 20.7 of the xepersian package.

**Comment by vafa** [comment]
I now accept donations to the xepersian package. Anyone can donate any amount to the xepersian package. If you are interested to donate to the xepersian package, then please email me at `persian-tex@tug.org` and request my bank account details.

The donations allow me to spend more time working on the xepersian package and make it even better. If you know that some other people may also be interested in donating to the xepersian package development, please let them know.
