### ISSUE TITLE
An issue when using \narrowdown from mathtools

### ISSUE THREAD

**Issue by srazi** [tex-xet/xepersian#40]
## Brief outline of the bug
When using `\narrowdown` from `mathtools`, the text after command will be rotated. If I remove `xepersian` the document will be rendered correctly.

## Your minimal example showing the bug

```latex
\documentclass{article}

\usepackage{amssymb}
\usepackage{mathtools}

\usepackage[%
    % Any xepersian package option goes here
]{xepersian}
\settextfont{Yas}

  % Any xepersian package commands goes here
  
\begin{document}

As an example, $\frac{1}{n}(1,0)\geq (0,1) > (0,0)$ for each $n\in\mathbb{N}$. Therefore, $\frac{1}{n}(1,0)\ndownarrow 0$.
The lexicographic order fails to have one property that the usual order on the reals has.
  
\end{document}
```

## Log (and possibly PDF) file  
[narrow-bug-en.log](https://github.com/tex-xet/xepersian/files/1634037/narrow-bug-en.log)
[narrow-bug-en.pdf](https://github.com/tex-xet/xepersian/files/1634038/narrow-bug-en.pdf)

**Comment by vafa** [comment]
Thanks for your bug report. This is not the expected behavior. It occurs to me that your TeXLive is not up to date. Please update your texlive.

I do not see any problem with updated texlive on my sistem. I have attached my log and PDF.

[test.log](https://github.com/tex-xet/xepersian/files/1634472/test.log)
[test.pdf](https://github.com/tex-xet/xepersian/files/1634474/test.pdf)

**Comment by vafa** [comment]
I now accept donations to the xepersian package. Anyone can donate any amount to the xepersian package. If you are interested to donate to the xepersian package, then please email me at `persian-tex@tug.org` and request my bank account details.

The donations allow me to spend more time working on the xepersian package and make it even better. If you know that some other people may also be interested in donating to the xepersian package development, please let them know.
