### ISSUE TITLE
 The full stop character between numbers in text changes the order of numbers .

### ISSUE THREAD

**Issue by shapour-m** [tex-xet/xepersian#41]
## Brief outline of the issue
When we use  the full stop character between numbers in  text, it will change the order. 
Thanks.

## Minimal example showing the issue

```tex
\documentclass[a4paper,12pt]{article}
\usepackage[%
inlinemathdigits=persian,%
displaymathdigits=persian%
]{xepersian}
\settextfont[Scale=1.2]{IRZar}
\settextdigitfont[Scale=1]{Yas}
\setmathdigitfont[Scale=1]{PGaramond}
\begin{document}
عدد 13.96 که در لابلای متن نوشته شود خروجی درستی ندارد اما اگر به صورت
\lr{13.96}
و یا
$13.96$
نوشته شود خروجی درستی دارد.
 
\end{document}


```

## Log and PDF files 
[untitled-1.pdf](https://github.com/tex-xet/xepersian/files/1644537/untitled-1.pdf)
[untitled-1.log](https://github.com/tex-xet/xepersian/files/1644538/untitled-1.log)

**Comment by vafa** [comment]
This is done on purpose for handling section numbers, equation numbers and any other numbering which may occur throughout the document.

**Comment by shapour-m** [comment]
Ok. Thanks.

**Comment by vafa** [comment]
I now accept donations to the xepersian package. Anyone can donate any amount to the xepersian package. If you are interested to donate to the xepersian package, then please email me at `persian-tex@tug.org` and request my bank account details.

The donations allow me to spend more time working on the xepersian package and make it even better. If you know that some other people may also be interested in donating to the xepersian package development, please let them know.

**Comment by Elfengour** [comment]
This issue here also inverse decimal numbers in tables like 20.1 becomes 1.20
