### ISSUE TITLE
The problem in simultaneous use two packs xepersian and easylist

### ISSUE THREAD

**Issue by AzadnejadAli** [tex-xet/xepersian#44]
## Brief outline of the issue
The following file is executed without calling the `xepersian` package (or without the `\NewList` command) without error. But now it makes a error.

## Minimal example showing the issue

```tex
\documentclass{article}
\usepackage[at]{easylist}
\usepackage{xepersian}
\settextfont{Yas}
\begin{document}
\begin{easylist}\NewList
@
\end{easylist}
\end{document}
```

## Log and PDF files 
[1.log](https://github.com/tex-xet/xepersian/files/1735222/1.log)

**Comment by vafa** [comment]
The `biditools` package has a control sequence `\NewList` which has a different definition from the one provided by `easylist` package and does something entirely so this will make a clash. The fix is easy; you can save one definition and use it.

````tex
\documentclass{article}
\usepackage[at]{easylist}
\let\NEWLIST\NewList
\usepackage{xepersian}
\settextfont{Yas}
\begin{document}
\begin{easylist}\NEWLIST
@
\end{easylist}
\end{document}
````

**Comment by AzadnejadAli** [comment]
Thank you very much for your help.
