### ISSUE TITLE
How to place a Persian text around a path?

### ISSUE THREAD

**Issue by ghost** [tex-xet/xepersian#5]
Placing Persian text around a path has two problems:

1. The direction of the text is wrong and can not be changed;

2. The Persian letters are disjoined.

tex-xet/bidi#16 addresses the first issue while the second issue should be fixed in the `xepersian` package.

````latex
\documentclass{article}
\usepackage{tikz}
\usetikzlibrary{decorations.text}
\usepackage{xepersian}
\settextfont{Yas}
\begin{document}
\begin{tikzpicture}
\path [postaction={decorate,decoration={raise=-1ex,text along path, text align=center,
text={این یک تست است تا بتوان حول یک دایره نوشت}}}] (0,0) circle (2);
\end{tikzpicture}
\end{document}
````

This question was originally posted [here](http://qa.parsilatex.com/10048).

**Comment by vafa** [comment]
`tikz` provides a way to achieve this already. See [this question and answer](https://tex.stackexchange.com/questions/410820).
